//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuyenDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TinTuyenDung()
        {
            this.UngTuyens = new HashSet<UngTuyen>();
        }
    
        public int ID_TTD { get; set; }
        public string TieuDe { get; set; }
        public string YeuCau { get; set; }
        public string TgLam { get; set; }
        public Nullable<System.DateTime> HanUT { get; set; }
        public Nullable<int> SoLuongTD { get; set; }
        public string PhucLoi { get; set; }
        public string MucLuong { get; set; }
        public string CapBac { get; set; }
        public Nullable<System.DateTime> TgDang { get; set; }
        public string TrangThaiTTD { get; set; }
        public Nullable<System.DateTime> TgianCapNhatTT { get; set; }
        public Nullable<int> ID_Admin { get; set; }
        public Nullable<int> ID_NTD { get; set; }
        public Nullable<int> ID_CV { get; set; }
        public Nullable<bool> Xoa { get; set; }
    
        public virtual CongViec CongViec { get; set; }
        public virtual ND_Admin ND_Admin { get; set; }
        public virtual NhaTuyenDung NhaTuyenDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UngTuyen> UngTuyens { get; set; }
    }
}
